spring:
  application:
    name: ecommerce
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    show-sql: false  # datasource-proxy가 대신 찍으므로 false
    hibernate:
      ddl-auto: update  # Flyway 제거하고 JPA로 스키마 관리
      default-batch-fetch-size: 100
    defer-datasource-initialization: true  # JPA 스키마 생성 후 data.sql 실행

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false  # Flyway 비활성화

logging:
  level:
    p6spy: DEBUG
