server:
  port: 8081

spring:
  application:
    name: ecommerce
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    show-sql: false  # datasource-proxy가 대신 찍으므로 false
    hibernate:
      ddl-auto: update  # Flyway 제거하고 JPA로 스키마 관리
      default-batch-fetch-size: 100
    defer-datasource-initialization: true  # JPA 스키마 생성 후 data.sql 실행

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false  # Flyway 비활성화

  # Kafka 설정
  # 세부 설정은 KafkaProducerConfig, KafkaErrorHandlingConfig에서 관리
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 브로커 주소 (환경별로 다를 수 있음)
    consumer:
      group-id: ecommerce-order-consumer-group  # 기본 컨슈머 그룹 ID

logging:
  level:
    p6spy: DEBUG

# 쿠폰 발급 큐 설정
coupon:
  stream:
    consumer-group: coupon-consumer-group  # Redis Stream Consumer Group 이름
    consumer-name: consumer-1               # Consumer 인스턴스 이름 (수평 확장 시 변경 해야함)
