server:
  port: 8081

spring:
  application:
    name: ecommerce
  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    show-sql: false  # datasource-proxy가 대신 찍으므로 false
    hibernate:
      ddl-auto: update  # Flyway 제거하고 JPA로 스키마 관리
      default-batch-fetch-size: 100
    defer-datasource-initialization: true  # JPA 스키마 생성 후 data.sql 실행

    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: false  # Flyway 비활성화

  # Kafka 설정
  kafka:
    bootstrap-servers: localhost:9092  # Kafka 브로커 주소
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all  # 모든 복제본이 메시지를 받았는지 확인 (안정성 최대)
      retries: 3  # 전송 실패 시 재시도 횟수
    consumer:
      group-id: ecommerce-order-consumer-group  # 컨슈머 그룹 ID
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest  # 처음부터 메시지 읽기
      enable-auto-commit: false  # 수동 커밋 (메시지 처리 완료 후 커밋)
      properties:
        spring.json.trusted.packages: "*"  # JSON 역직렬화 신뢰 패키지 (보안상 실제로는 제한 필요)

logging:
  level:
    p6spy: DEBUG

# 쿠폰 발급 큐 설정
coupon:
  stream:
    consumer-group: coupon-consumer-group  # Redis Stream Consumer Group 이름
    consumer-name: consumer-1               # Consumer 인스턴스 이름 (수평 확장 시 변경 해야함)
